name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dotfiles
      run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply unvalley